---
- name: Help
  description: "Help page display this file"
  url: /help
  # Configure autorisations
  grant:
    # This activates basic auth on the service, users are defined in users.yml
    local_user:
      - user1
      - user2
    # This needs extra configuration with external authenticator, see README.md
    x_remote_user:
      - remote_user1
      - remote_user2
    x_group:
      - group1
      - group2
  cmd: bat --plain --color always config.yml

- name: Rainbow
  description: "Test word highlights and stream"
  url: /rainbow
  cmd: ./tests/rainbow.sh
  # 'word' and 'line' support RegExp
  # 'class' could be any class define in public/css/custom.css
  highlight:
    # 'word' highlight only matching word
    - word: '^[0-9]+'
      class: bold
    - word: 'hide'
      class: hide
    # 'line' highlight only matching line
    - line: '10'
      class: italic

- name: Args
  description: "Test args, suburls, password and plain text"
  url: /args/test
  # Set a password to query url as "?password=suburlpass"
  password: suburlpass
  # Whitelist some specific chars for that service
  whitelist: ["(", ")", " "]
  # curl -Gs --data-urlencode "hostname=( f o o )" "http://localhost:3000/shellcast/args/test/plain?mac=00:11:22:33:44:55&password=suburlpass"
  # will be run as './tests/args.sh "(f o o)" "192.168.0.1" "00:11:22:33:44:55"'
  cmd: ./tests/args.sh "{hostname}" "{x_forwarded_for}" "{mac}" "{hostname} has ip {x_forwarded_for} and mac {mac}"
  args:
    - hostname
    - mac
